### PR TITLE
gui_c.lua

### PR DESCRIPTION
**Pull request by michael86**
Was testing my server for xss and seems EasyAdmin is vulnerable as well? Added a quick function to strip steam name of special chars. Truth be told, you could probably find a much more efficient way of doing this. My way simply strips there steam name of special chars before adding it to the menu and running any malicious script. 

I.E 
<script src="http://somecrap">

would become
"somecrap"

The name is sent to the function on line 158. 

Function starts on line 531

### CODE REVIEW

**Comment by Bluethefurry** [comment]
huh, this sounds more like a NativeUI issue though, in which way is it vulnerable to xss? we don't use nui so webpages and the lot shouldn't work

**Comment by michael86** [comment]
aye that's what I would have thought, was very surprised when I see it. I basically changed my steam name to a script that a bunch of twats are currently using and it run it! If you're on discord, I can send you the script on there so you can test it.

**Comment by michael86** [comment]
Just set my steam name to <script> and this is the result. [https://imgur.com/PXlyOYB](url)

It's not displaying it, so something is detecting the html properties?

**Comment by Bluethefurry** [comment]
Can you try using
```<script>alert("hi")</script>```
see if that works?

**Comment by Bluethefurry** [comment]
also checked the pinned issue for a discord.

**Comment by michael86** [comment]
okay, tried it and it seems it strips the html already? [https://imgur.com/HpAkZxG](url)

**Comment by Bluethefurry** [comment]
so this is probably not an issue then, i would check your other resources, since easyadmin does not seem vulnerable from here.

**Pull request closed without merging**
