### PR TITLE
Update admin_client.lua

### PR DESCRIPTION
**Pull request by yagizher**
Screenshots fixed.The website was closed and updated it with the new website.

### CODE REVIEW

**Comment by Bartixxx32** [comment]
have you tested? becouse my pullreq, was edited a bunch of code and it can stop work, my work for 0x0.st

**Comment by yagizher** [comment]
Yes.With the support of your editing, i think i did it.

**Comment by Rubylium** [comment]
Not working on my side by just changing the URL, did you change something on the server side ?

**Comment by Bluethefurry** [comment]
closed due to inactivity, reopen it if you intend on updating it

**Pull request closed without merging**
