### PR TITLE
OneSync Infinity/Big Mode | Teleport fix(Teleport To Player and Teleport Player to Me)

### PR DESCRIPTION
**Pull request by LeCyreaxYT**
Here ist a Pull Request for this

i have supported 2 Version

EssentialsMode for old Server and es_extended for the Newest Version
VRP are not supported!

Convar:
set ea_essentialsorextended "1" -- // 1 = essentialsmode and 0 = es_extended // --

### CODE REVIEW

**Comment by Bluethefurry** [comment]
I'd much rather not have a version that depends on any outside resource like essentialmode or ESX, EasyAdmin can easily do this without such, i would recommend making a standalone solution for this instead.

**Comment by LeCyreaxYT** [comment]
I will edit this and make it in EasyAdmin

**Comment by LeCyreaxYT** [comment]
I've looked into it and haven't been able to change it. If you have an idea that's standalone, you're welcome to bring it to me.

but if you want you can add a standalone variable so that all 3 go or you can do only 1.

**Comment by Bluethefurry** [comment]
`If you have an idea that's standalone, you're welcome to bring it to me.`
I'd look at the util functions esx or whatever you use provides, and then port them to something we can use, even if it requires firing events back and forth, for exmaple


admin requests tp > server asks target for coords > client sends coords > server sends cords to admin > admin tps

**Comment by Bluethefurry** [comment]
closed due to inactive maintainer, feel free to re-open if you continue working on this pr.

**Pull request closed without merging**
